spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_db
spring.datasource.username=cadastro_user
spring.datasource.password=Jp#9Lx!72@QvR5$k
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always
